server:
  port: 8080

spring:
  application:
    name: ms-recursos

  datasource:
    url: jdbc:postgresql://postgres-recursos:5432/recursos_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # o validate en producci√≥n
    show-sql: true
    properties:
      hibernate:
        format_sql: true
