version: "3.8"

services:
  postgres-clientes:
    image: postgres:15
    container_name: postgres-clientes
    environment:
      POSTGRES_DB: clientes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - clientes_data:/var/lib/postgresql/data

  ms-clientes:
    build: ./ms-clientes
    container_name: ms-clientes
    depends_on:
      - postgres-clientes
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-clientes:5432/clientes_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8082:8082"

volumes:
  clientes_data:
