server:
  port: 8081 # El puerto en el que corre la app DENTRO del contenedor

spring:
  application:
    name: ms-camiones

  # ¡BORRAMOS TODA LA SECCIÓN 'datasource'!
  # Docker-compose se la dará ahora.

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    # ¡BORRAMOS 'ddl-auto'! Docker-compose se lo dará.

    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # ¡BORRAMOS TODA LA SECCIÓN 'security.oauth2'!
  # Docker-compose se la dará.
